---
- hosts: web_servers
  become: true
  tasks:
    # Update apt package cache
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    # Install basic packages
    - name: Install basic packages
      ansible.builtin.package:
        name:
          - curl
          - git
          - build-essential
          - vim
          - htop
          - wget
          - unzip
          - tree
        state: present

    # Install Python pip
    - name: Install Python pip
      ansible.builtin.package:
        name: python3-pip
        state: present

    # Install Docker dependencies
    - name: Install Docker dependencies
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - gnupg
        state: present

    # Add Docker's official GPG key
    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Add Docker repository
    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: yes

    # Install Docker
    - name: Install Docker
      ansible.builtin.package:
        name: docker-ce
        state: present

    # Install Docker Compose
    - name: Install Docker Compose
      ansible.builtin.pip:
        name: docker-compose

    # Upgrade all installed packages to the latest version
    - name: Upgrade all installed packages to the latest version
      ansible.builtin.apt:
        upgrade: yes

    # Add user 'daniel' to the 'docker' group
    - name: Add user 'daniel' to the 'docker' group
      ansible.builtin.user:
        name: daniel
        groups: docker
        append: yes

    # Reload systemd to apply group changes
    - name: Reload systemd to apply changes
      ansible.builtin.systemd:
        daemon_reload: yes

    # Perform a dist-upgrade for full package upgrades
    - name: Perform a dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
