---
- hosts: web_servers
  become: true
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install basic packages
      ansible.builtin.package:
        name:
          - curl
          - git
          - build-essential
          - vim
          - htop
          - wget
          - unzip
          - docker.io
          - docker-compose
          - python3
          - tree
        state: present

    - name: Install Python pip
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Upgrade all installed packages to latest version
      ansible.builtin.apt:
        upgrade: yes
