---
- hosts: web_servers
  become: true
  tasks:
    - name: Add user 'daniel' to the 'docker' group
      ansible.builtin.user:
        name: daniel
        groups: docker
        append: yes

    - name: Reload systemd to apply changes
      ansible.builtin.systemd:
        daemon_reload: yes
