---
- hosts: web_servers
  become: true
  tasks:
     # Remove Docker Compose with the --break-system-packages flag
    - name: Remove Docker Compose with --break-system-packages
      ansible.builtin.command: 
        cmd: "/usr/bin/python3 -m pip uninstall -y docker-compose --break-system-packages"
      ignore_errors: yes
    
    # Purge Docker and its related packages
    - name: Purge Docker and its dependencies
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent
        purge: yes


    # Remove Docker repository from apt sources
    - name: Remove Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: absent

    # Remove Docker GPG key by specifying the key ID
    - name: Remove Docker GPG key
      ansible.builtin.apt_key:
        id: '0EBFCD88'
        state: absent
        
    # Purge basic packages (curl, git, build-essential, etc.)
    - name: Purge basic packages
      ansible.builtin.package:
        name:
          - curl
          - git
          - build-essential
          - vim
          - htop
          - wget
          - unzip
          - python3-pip
          - tree
        state: absent
        purge: yes

    # Remove Docker directories and files
    - name: Remove Docker directories and files
      ansible.builtin.file:
        path: /var/lib/docker
        state: absent

    # Remove the user 'daniel' from the 'docker' group
    - name: Remove 'daniel' from the 'docker' group
      ansible.builtin.user:
        name: daniel
        groups: docker
        append: no
        state: present

    # Reload systemd after group and package changes
    - name: Reload systemd to apply changes
      ansible.builtin.systemd:
        daemon_reload: yes
